# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15871e3383a764ed0345a8c998514719ee1f9d1b950a231f68a27cac36a4d6c8b58352dab8aa4fb52e8ca4d51fcfcd84eb0d4d4b746ab5d35acdbd5c3befd9c6

test:
  secret_key_base: f1e162c02c175be8593c8f5e3569db9bfc0136484f30e2df0ed9d162285576c495bd67819fba4ef1b88c21ddb151c962a7f0ae1202ff1e6c50a83fc14099f63f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
